export type SeasonComp = {
  slug: string;
  name: string;
  claimCode: string;
  eventDate: Date;
  dates: string;
  location: string;
  venue: string;
  acceptingApps?: boolean;
};

/** Official bid listings. Codes are also listed in COMP_CODES.md — treat them as secrets. */
export const SEASON_COMPS: SeasonComp[] = [
  {
    slug: "legends",
    name: "Legends",
    claimCode: "LGND-7K2M",
    eventDate: new Date("2026-04-18"),
    dates: "Apr 18, 2026",
    location: "Charlotte, NC",
    venue: "TBA",
  },
  {
    slug: "tufaan",
    name: "Tufaan",
    claimCode: "TFAN-9Q4R",
    eventDate: new Date("2026-03-21"),
    dates: "Mar 21, 2026",
    location: "Houston, TX",
    venue: "TBA",
  },
  {
    slug: "gateway-to-india",
    name: "Gateway to India",
    claimCode: "GTI-3H8P",
    eventDate: new Date("2026-03-21"),
    dates: "Mar 21, 2026",
    location: "Dallas, TX",
    venue: "TBA",
  },
  {
    slug: "aa-dekhen-zara",
    name: "Aa Dekhen Zara",
    claimCode: "ADZ-6N5W",
    eventDate: new Date("2026-03-14"),
    dates: "Mar 14, 2026",
    location: "Stony Brook, NY",
    venue: "TBA",
  },
  {
    slug: "norman-nachle",
    name: "Norman Nachle",
    claimCode: "NRMN-2B7C",
    eventDate: new Date("2026-03-07"),
    dates: "Mar 7, 2026",
    location: "Norman, OK",
    venue: "TBA",
  },
  {
    slug: "aaj-ka-dhamaka",
    name: "Aaj Ka Dhamaka",
    claimCode: "AKD-8F3Y",
    eventDate: new Date("2026-03-07"),
    dates: "Mar 7, 2026",
    location: "New Brunswick, NJ",
    venue: "TBA",
  },
  {
    slug: "naach-di-cleveland",
    name: "Naach Di Cleveland",
    claimCode: "NDC-4T9K",
    eventDate: new Date("2026-02-28"),
    dates: "Feb 28, 2026",
    location: "Cleveland, OH",
    venue: "TBA",
  },
  {
    slug: "legacy-on-broad",
    name: "Legacy on Broad",
    claimCode: "LGBR-5M1X",
    eventDate: new Date("2026-02-28"),
    dates: "Feb 28, 2026",
    location: "Philadelphia, PA",
    venue: "TBA",
  },
  {
    slug: "jazba",
    name: "Jazba",
    claimCode: "JZBA-7P6D",
    eventDate: new Date("2026-02-28"),
    dates: "Feb 28, 2026",
    location: "College Park, MD",
    venue: "TBA",
  },
  {
    slug: "bollywood-berkeley",
    name: "Bollywood Berkeley",
    claimCode: "BBRK-1Q8H",
    eventDate: new Date("2026-02-28"),
    dates: "Feb 28, 2026",
    location: "Berkeley, CA",
    venue: "TBA",
  },
  {
    slug: "nj-naach",
    name: "NJ Naach",
    claimCode: "NJN-9C4V",
    eventDate: new Date("2026-02-21"),
    dates: "Feb 21, 2026",
    location: "New Brunswick, NJ",
    venue: "TBA",
  },
  {
    slug: "magic-city-maza",
    name: "Magic City Maza",
    claimCode: "MCM-3R7J",
    eventDate: new Date("2026-02-21"),
    dates: "Feb 21, 2026",
    location: "Birmingham, AL",
    venue: "TBA",
  },
  {
    slug: "knoxville-ki-jawaani",
    name: "Knoxville Ki Jawaani",
    claimCode: "KKJ-6W2S",
    eventDate: new Date("2026-02-21"),
    dates: "Feb 21, 2026",
    location: "Knoxville, TN",
    venue: "TBA",
  },
  {
    slug: "tamasha-sd",
    name: "Tamasha SD",
    claimCode: "TMSD-8L5N",
    eventDate: new Date("2026-02-14"),
    dates: "Feb 14, 2026",
    location: "San Diego, CA",
    venue: "TBA",
  },
  {
    slug: "midwest-dhamaka",
    name: "Midwest Dhamaka",
    claimCode: "MWD-2Y9G",
    eventDate: new Date("2026-02-14"),
    dates: "Feb 14, 2026",
    location: "Chicago, IL",
    venue: "TBA",
  },
  {
    slug: "jhalak",
    name: "Jhalak",
    claimCode: "JHLK-4D8Q",
    eventDate: new Date("2026-02-14"),
    dates: "Feb 14, 2026",
    location: "Madison, WI",
    venue: "TBA",
  },
  {
    slug: "aaja-nachle",
    name: "Aaja Nachle",
    claimCode: "AJN-7H3B",
    eventDate: new Date("2026-02-14"),
    dates: "Feb 14, 2026",
    location: "Ann Arbor, MI",
    venue: "TBA",
  },
  {
    slug: "uga-india-night",
    name: "UGA India Night",
    claimCode: "UGA-5K1F",
    eventDate: new Date("2026-02-07"),
    dates: "Feb 7, 2026",
    location: "Athens, GA",
    venue: "TBA",
  },
  {
    slug: "blacksburg-ki-badmaashi",
    name: "Blacksburg Ki Badmaashi",
    claimCode: "BKB-9T6M",
    eventDate: new Date("2026-02-07"),
    dates: "Feb 7, 2026",
    location: "Blacksburg, VA",
    venue: "TBA",
  },
  {
    slug: "maryland-minza",
    name: "Maryland Minza",
    claimCode: "MINZ-3P8W",
    eventDate: new Date("2026-01-24"),
    dates: "Jan 24, 2026",
    location: "College Park, MD",
    venue: "TBA",
  },
  {
    slug: "buckeye-mela",
    name: "Buckeye Mela",
    claimCode: "BCKY-1N4R",
    eventDate: new Date("2026-01-24"),
    dates: "Jan 24, 2026",
    location: "Columbus, OH",
    venue: "TBA",
  },
  {
    slug: "aag-ki-raat",
    name: "Aag Ki Raat",
    claimCode: "AKR-8C2Y",
    eventDate: new Date("2026-01-24"),
    dates: "Jan 24, 2026",
    location: "University Park, PA",
    venue: "TBA",
  },
  {
    slug: "atl-tamasha",
    name: "ATL Tamasha",
    claimCode: "ATL-6J7K",
    eventDate: new Date("2025-11-22"),
    dates: "Nov 22, 2025",
    location: "Atlanta, GA",
    venue: "TBA",
    acceptingApps: false,
  },
];

